game:
  scenario: 01-race-to-contain-power
  win_threshold: 67
  max_rounds: 7
  roll_success_threshold: 14
  action_time_cost_years: 0.4
  enabled_factions:
    - Governments
    - Corporations
    - HardwareManufacturers
    - Regulators
    - CivilSociety
    - ScientificCommunity
  player_faction: CivilSociety
  format_prompt_character_limit: 300
  conversation_force_action_after: 6
